global using Booking.Api;
global using Booking.Application.Commands;
global using Booking.Application.Queries;
global using Booking.Application.Queries.ViewModels;
global using Booking.Application.Services.Identity;
global using Booking.Infrastructure;
global using MediatR;
global using Microsoft.AspNetCore.Http.HttpResults;
global using Microsoft.AspNetCore.Mvc;
